### ISSUE TITLE
VanitySlots v2.0.0 causes runtime exception

### ISSUE THREAD

**Issue by lluxia** [NyakoFox/VanitySlots-Multiloader#2]
Hello, the new version of VanitySlots fails to start my 1.21.1 server with the following message:

> [23:59:42] [main/ERROR]: Failed to start the minecraft server
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vanityslots' at 'gay.nyako.vanityslots.VanitySlotsMod'!
>         at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.3.jar:?]
>         at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.3.jar:?]
>         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.3.jar:?]
>         at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.3.jar:?]
>         at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
>         at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
>         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
>         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
>         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/item/Item
>         at gay.nyako.vanityslots.VanitySlotsMod.onInitialize(VanitySlotsMod.java:13) ~[%5BB%5D%5B1.21.1%5D%20VanitySlots%202.0.0%20%5BAccessories+FAPI+FCAPI%5D.jar:?]
>         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
>         ... 6 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.world.item.Item
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
>         at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.3.jar:?]
>         at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.3.jar:?]
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
>         at gay.nyako.vanityslots.VanitySlotsMod.onInitialize(VanitySlotsMod.java:13) ~[%5BB%5D%5B1.21.1%5D%20VanitySlots%202.0.0%20%5BAccessories+FAPI+FCAPI%5D.jar:?]
>         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
>         ... 6 more
> 
> F:\Fabric Loader [1.21.1]>PAUSE
> Press any key to continue . . .

**Comment by NyakoFox** [comment]
Sorry, I uploaded the wrong jar to Modrinth. If you redownload it, it should work now!
