### ISSUE TITLE
QUESTION NOT ISSUE 

### ISSUE THREAD

**Issue by R0gyman** [NyakoFox/VanitySlots-Multiloader#4]
Im trying to make a resource pack to make the icons transparent but I can't find the background texture for the icons, I can find the icons themselves but not the background. by chance do you know what the file is called?

**Comment by NyakoFox** [comment]
Are you using a version with Accessories or Trinkets? Either way, you might want to look into them -- they handle the extra slot rendering.

**Comment by R0gyman** [comment]
Trinkets, ive made other slots transparent I just cant find the background texture on this pack

if you cant help don't worry about it

**Comment by NyakoFox** [comment]
They're [over here](https://github.com/NyakoFox/VanitySlots-Legacy/tree/1.20.1/src/main/resources/assets/vanityslots/textures/gui)

**Comment by R0gyman** [comment]
you can close this thanks!
